### PR TITLE
Update MF2 Syntax to 2023-12-18 version

### LINKED ISSUE #18: Update MF2 syntax to 2023.18.12 version
[ABNF](https://github.com/unicode-org/message-format-wg/blob/86cc16b05a86214c22233f71efe18ef1c162c220/spec/message.abnf)

[DIFF](https://github.com/unicode-org/message-format-wg/commit/86cc16b05a86214c22233f71efe18ef1c162c220)

### PR DESCRIPTION
**Pull request by VladislavsPerkanuks**
Closes #18

### CODE REVIEW

**Comment by janishorsts** [comment]
We should provide ABNF diff for these changes to make it clearer what changed. Can you please provide diff?

**Comment by VladislavsPerkanuks** [comment]
check issue

**Comment by janishorsts** [comment]
It has the link to the ABNF file but no diff.

**Comment by VladislavsPerkanuks** [comment]
it has
image

**Review by janishorsts — APPROVED** [review]

**Pull request merged**
